meta_product_name: "Abstention aux Municipales - 2020"
meta_title: "Abstention aux Municipales - 2020"
meta_description: "Cartographie de l'abstention du premier tour des municipales en 2020"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
